name = "retwik-api"
main = "src/index.ts"
compatibility_date = "2025-04-28"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "retwik_db"
database_id = "75baefe1-bbab-44dd-b765-47f403de4660"
migrations_dir = "drizzle/migrations"

[observability.logs]
enabled = true

[vars]
ALLOWED_ORIGINS = "http://localhost:3000,https://retwik-api.crsssssk.workers.dev"
BETTER_AUTH_URL = "https://retwik-api.crsssssk.workers.dev"
BUCKET_PUBLIC_URL = "https://pub-8885b6d8afb6420387a1bd5f3e53e364.r2.dev"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "R2"
bucket_name = "retwik-bucket"
