-- Migration number: 0002 	 2025-05-06T17:37:08.502Z
CREATE TABLE IF NOT EXISTS videos (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 transcript TEXT NOT NULL,
 audio_urls TEXT,
 video_url TEXT NOT NULL,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
